steps:
  # Step 1: Clone the Java Spring Boot project from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--branch=$BRANCH_NAME'
      - 'https://github.com/technical-stuff/spring3.git'
      - '/test3'
      
  - name: 'alpine'
    args:
      - 'sh'
      - '-c'
      - |
        ls -a
        pwd
        whoami
        
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
        
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: 
  #    - 'clean'
  #    - 'install'
  #    - '/test3'
  
    # Step 2: Run Maven clean install
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - '-f'
      - '/workspace/pom.xml'  # Adjust the path to your pom.xml file
      - 'clean'
      - 'install'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/eastern-dream-404606/testing/$BRANCH_NAME:$BRANCH_NAME'
      - '.'

  # Step 3: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/eastern-dream-404606/testing/$BRANCH_NAME:$BRANCH_NAME'

  # Authenticate with Google Cloud and set project and region
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project $PROJECT_ID
        gcloud config set compute/region us-east1

        # Get cluster credentials and set the context
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-east1 --project $PROJECT_ID

        # Verify the namespaces
        kubectl config get-contexts

        # Get the list of namespaces
        kubectl get namespace
      
   # Print the contexts and namespaces to the Cloud Build logs
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Kubernetes Contexts:"
        kubectl config get-contexts  # Access the Kubernetes contexts

        echo "Namespaces:"
        kubectl get namespace  # Access the list of namespaces

  # Print the cluster info to the Cloud Build logs
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cluster Info:"
        kubectl cluster-info  # Access the cluster info

  # Print the namespaces to the Cloud Build logs
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Namespaces:"
        echo $${_GET_NAMESPACES}  # Access the output variable
        
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: 'bash'
   args:
     - '-c'
     - |
     - 'kubectl apply -f /workspace/namespace.yaml'
images:
  - 'us-east1-docker.pkg.dev/eastern-dream-404606/testing/$BRANCH_NAME:$BRANCH_NAME'
options:
  logging: CLOUD_LOGGING_ONLY
